#!/bin/bash

if
	[ -z "$(command -v tmux)" ] || # tmux is not installed
	[ -n "$TMUX" ]           || # already inside tmux
	[ "$TERM" == 'screen' ]  ;  # inside screen
then
	return;
fi

TPM_FOLDER="$HOME/.tmux/plugins/tpm"
if [ ! -d "$TPM_FOLDER" ] ; then
	git clone 'https://github.com/tmux-plugins/tpm' "$TPM_FOLDER"
fi

tmux attach ||                  # attach to a session if it exists
exec tmux new-session && exit;  # otherwise, start a new one
